version: "3.9"
services:
  tinydns:
    container_name: tinydns
    network_mode: bridge
    build: tinydns
    volumes:
      - ./data:/etc/tinydns/root/data:ro
  ssh:
    container_name: updater
    network_mode: bridge
    build: ssh
    volumes:
      - ./data:/home/dyndns/data
      - ./id_rsa.pub:/home/dyndns/.ssh/authorized_keys  # this must be owned by 1000 (dyndns user in container) and have permissions 600
